# action.yml
name: "Test Analyzer Github Action"
description: "upload and track testing artifacts for summary and support"
inputs:
  junit-location:
    description: "location of junit report"
    required: true
    default: "./junit.xml"
  type:
    description: "test report type: unit, integration, e2e"
    required: true
  key:
    description: "api key associated to your team"
    required: true
  coverage-location:
    description: "file location of lcov coverage report"
    required: false
    default: "coverage/lcov.info"

outputs:
  run-url:
    description: "test analysis url"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.junit-location }}
    - ${{ inputs.coverage-location }}
